# Generated by Django 5.2.8 on 2025-12-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='text',
            new_name='topic_name',
        ),
    ]
