# Generated by Django 5.2.8 on 2025-12-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_text_topic_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='entry',
        ),
    ]
