# Generated by Django 5.2.8 on 2025-12-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
    ]
