# Generated by Django 5.2.8 on 2025-12-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='current_streal',
            new_name='current_streak',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_entry_data',
            new_name='last_entry_date',
        ),
    ]
